<?php

define('TFFC_IMPORT_ENABLED', FALSE);
define('TFFC_IMPORT_SYNC', FALSE);
define('TFFC_IMPORT_CRON_AMOUNT', 1);
define('TFFC_IMPORT_DEFAULT_LAST_ID', 'tt00000001');
define('TFFC_IMPORT_DEFAULT_VOTES', '1000');
define('TFFC_IMPORT_DEFAULT_RATING', '3.2');
define('TFFC_IMPORT_DEFAULT_TYPE', 'any');
define('TFFC_IMPORT_DEFAULT_RELEASE', '1960-01-01');

/**
 * hook_cron
 */
function tffc_importer_cron() {
  $watchdog = \Drupal::logger('tffc_importer');
  $tffc_config = \Drupal::config('tffc_importer.settings');
  $importer_enabled = $tffc_config->get('enabled') ?? TFFC_IMPORT_ENABLED;
  $sync_enabled = $tffc_config->get('sync') ?? TFFC_IMPORT_SYNC;
  $import_amount = $tffc_config->get('import_amount') ?? TFFC_IMPORT_CRON_AMOUNT;

  // if enabled import one
  if ($importer_enabled) {

    /**
     * @var \Drupal\tffc_importer\Services\TffcImporter
     */
    $TffcImporter = \Drupal::service('tffc.importer');

    if (is_numeric($import_amount) && $import_amount > 0) {

      $response = $TffcImporter->importX($import_amount);

      if (!empty($response)) {
        $errors = $response['errors'];
        $success = $response['success'];
        $info = $response['info'];

        if (!empty($errors)) {
          foreach ($errors as $e) {
            $watchdog->error($e);
          }
        }

        if (!empty($info)) {
          foreach ($info as $i) {
            $watchdog->notice($i);
          }
        }

        if (!empty($success)) {
          foreach ($success as $s) {
            $watchdog->info($s);
          }
        }
      }

    }
  }

  if ($sync_enabled) {
    $TffcSync = \Drupal::service('tffc.sync');
    $sync = $TffcSync->getSyncableFilms();
    if (!empty($sync) && count($sync) > 0) {
      foreach ($sync as $nid) {

        $response = $TffcSync->syncInformation($nid);
        if (!empty($response)) {
          $errors = $response->getErrors();
          $success = $response->getSuccess();

          if (!empty($errors)) {
            foreach ($errors as $e) {
              $watchdog->error($e);
            }
          }

          if (!empty($success)) {
            foreach ($success as $s) {
              $watchdog->info($s);
            }
          }
        }
      }
    }
    else {
      $watchdog->info("Nothing to sync.");
    }
  }
}

